import { Toaster } from "react-hot-toast";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="antialiased bg-primary">
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
