import "../globals.css";
import Providers from "@/providers/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="antialiased bg-primary">
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
