import "../globals.css";
import SideBar from "@/components/Profile/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`antialiased bg-primary overflow-hidden`}>
        <main className="grid grid-cols-12 overflow-hidden">
          <section className="col-span-3 h-screen">
            <SideBar />
          </section>
          <section className="col-span-9">
            <header className="w-full h-10 bg-primary"></header>
            <main className="sticky top-10 left-0 w-full h-screen rounded-tr-2xl bg-bg-primary p-5 px-6 overflow-y-auto pb-20">
              {children}
            </main>
          </section>
        </main>
      </body>
    </html>
  );
}
