import Header from "@/components/Header";
import "../globals.css";
import Providers from "@/providers/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className="h-full">
      <Providers>
        <body className="antialiased bg-bg-primary h-full flex flex-col">
          <Header />
          <main className="flex-1 overflow-y-auto">
            <div className="pb-20">{children}</div>
          </main>
        </body>
      </Providers>
    </html>
  );
}
